# Generated by Django 3.2.14 on 2022-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filename', models.CharField(max_length=50, verbose_name='文件名')),
                ('detected_filename', models.CharField(max_length=50, verbose_name='文件名')),
                ('detect_result', models.CharField(max_length=10, verbose_name='检测结果')),
                ('create_date_time', models.DateTimeField(max_length=40, verbose_name='检测时间')),
            ],
            options={
                'verbose_name': '检测数据表',
                'verbose_name_plural': '检测数据表',
                'db_table': 'detected_img',
            },
        ),
    ]
