# Generated by Django 3.2.14 on 2022-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_role_data_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话', max_length=255, null=True, verbose_name='电话'),
        ),
    ]
