# Generated by Django 3.2.14 on 2022-10-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_operationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='datas',
        ),
    ]
