# Generated by Django 3.2.14 on 2022-10-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_role_datas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postion',
            new_name='Position',
        ),
        migrations.AlterModelTable(
            name='position',
            table='system_position',
        ),
    ]
